# Generated by Django 3.1 on 2020-10-05 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='', max_length=256)),
                ('country', models.CharField(default='', max_length=256)),
                ('temperature', models.IntegerField(blank=True, default=0)),
                ('feels_like', models.IntegerField(blank=True, default=0)),
                ('wind_speed', models.IntegerField(blank=True, default=0)),
                ('wind_direction', models.IntegerField(blank=True, default=0)),
                ('pressure', models.IntegerField(blank=True, default=0)),
                ('humidity', models.IntegerField(blank=True, default=0)),
                ('visibility', models.IntegerField(blank=True, default=0)),
                ('main', models.CharField(default='', max_length=256)),
                ('description', models.CharField(default='', max_length=256)),
                ('icon', models.CharField(default='', max_length=256)),
                ('measurement_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAirQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='', max_length=256)),
                ('pm1', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('pm25', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('pm10', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('index_value', models.IntegerField(blank=True, default=0)),
                ('index_level', models.CharField(default='', max_length=256)),
                ('index_description', models.CharField(default='', max_length=256)),
                ('index_color', models.CharField(default='', max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
