# Generated by Django 3.1 on 2020-10-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentweather',
            name='measurement_time',
        ),
    ]
