# Generated by Django 3.1 on 2020-10-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0003_currentweather_measurement_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentairquality',
            name='time',
        ),
        migrations.AddField(
            model_name='currentairquality',
            name='measurement_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
