# Generated by Django 3.1 on 2020-11-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0004_auto_20201020_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentweather',
            name='city_name',
            field=models.CharField(default='', max_length=256, verbose_name='City name'),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='country',
            field=models.CharField(default='', max_length=256, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='feels_like',
            field=models.IntegerField(blank=True, default=0, verbose_name='Feels like'),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='humidity',
            field=models.IntegerField(blank=True, default=0, verbose_name='Humidity'),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='measurement_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Measurement time'),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='pressure',
            field=models.IntegerField(blank=True, default=0, verbose_name='Pressure'),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='temperature',
            field=models.IntegerField(blank=True, default=0, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='visibility',
            field=models.IntegerField(blank=True, default=0, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='wind_direction',
            field=models.IntegerField(blank=True, default=0, verbose_name='Wind direction'),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='wind_speed',
            field=models.IntegerField(blank=True, default=0, verbose_name='Wind speed'),
        ),
    ]
