# Generated by Django 3.1 on 2020-11-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0005_auto_20201116_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentweather',
            name='city_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='country',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='feels_like',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='humidity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='measurement_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='pressure',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='temperature',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='visibility',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='wind_direction',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='wind_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
