# Generated by Django 3.1 on 2020-11-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0006_auto_20201117_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentairquality',
            name='pm1',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='currentairquality',
            name='pm10',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='currentairquality',
            name='pm25',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4),
        ),
    ]
