# Generated by Django 3.1 on 2020-12-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0009_auto_20201127_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentweather',
            name='visibility',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
